server:
  port: 8081
spring:
  datasource:
    url: ENC(ycijG4cGBLkf/ii6OFeyOr4KFYYhOEUlni6QxTOw4crmWwBLTMzvfRHDW/0HiNkw)
    username: ENC(tJ3Wayb9TrXUsh5F8P0rXA==)
    password: ENC(JufSsZZ1xe7aGFfBKs1VyHm5eHnoRlqg)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false

  jwt:
    secret: ENC(6FSLW23C9EzdXc9nnJlfLJIxbWOD6PY3S8eKTSRsWvq1+xgreWcXGzDXUmeZOI1qn3cHyOjvhl376Idb1ETVbQ3Km5Hg8GjvaLoOyFQs/4tKh411lMQ3YURNYf3iLrSC)
    accessTokenExpiration: 30000
    refreshTokenExpiration: 60000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

email:
  gmail:
    id: ENC(DR0J+Ify50+A4JkKuXg4HNrWkcgfy4XLwofhJqpir4Y=)
    pw: ENC(cbu0+ZLXCzeousUvSD8d8hxy93PPRmIWOONbdwKcjfk=)