server:
  port: 8081
spring:
  datasource:
    url: ENC(z44ecfCHQWJ1LOJYtYvXN1LAptvPipta9CcBBx4ZU6EZHlAor/pAYiA7DO+SOLWC39NcD91JvFYJ2+hXK6sioYToo9u2Use6eKlKAfJQMmST672IHaOPgg==)
    username: ENC(QKqkg2IetJ69NKczZl90lA==)
    password: ENC(ckyLlB3q4iXqt8HAzy6/5BRI+3V16Xkj)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
#      host: redis
      host: redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false

  jwt:
    secret: ENC(+aRqCgyZ/OYQJcpSI6fVSo5eepNxe9iDnZr56TdsWrn53jXuruExy70ErQd+Ry6uLcX+uRFjRoxQWZMmDHZk2XCZctkPfj4BlMguN0qGZcHtCMFhRkkoQQRvvACt7XF3)
    accessTokenExpiration: 300000
    refreshTokenExpiration: 600000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

cloud:
  aws:
    s3:
      bucket: ENC(m0bqTBTNC6vk8w/90xoxK2ejZ9/55cRWpuUQovjhf5Q=)
    region:
      auto: false
      static: ap-northeast-2
    credentials:
      accessKey: ENC(RF//cbj/2OzDVx7s2mMcgF33bl/9opqi3QdJdlOgJEo=)
      secretKey: ENC(D1JOF7dwKPdQqTj9H/PCxxID/CyD21FKFssst+lf4c7Frl1jDZj54cZk7UGaQ8qVhGZ36XnostY=)
    stack:
      auto: false
email:
  gmail:
    id: ENC(grcUGv0ZhfLq3FvUOsFPvcM0Tpe4gxFWk9nExZcQ8Ek=)
    pw: ENC(fUUkoxWc+OLQKP8/hsGwW9owcide1oR/2C/uGMdSU6I=)