server:
  port: 8081
spring:
  datasource:
    url: ENC(A/BmB7diTVtZvhZwpxY9PxAIDW7r2gUhsChkjbiYS90Ye3d0W2w7yGGfYTRdG8uJZoeaoVLnClghzfovpf3KsNEYbtLWuAZmavhmjYRwl9hLW5idWvekUg==)
    username: ENC(9LDHLh/heZX4rF26F6HlEA==)
    password: ENC(ygXYnU2QXgEsKR3wTnwmMPDJhw3eRw+G)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false

  jwt:
    secret: ENC(6FSLW23C9EzdXc9nnJlfLJIxbWOD6PY3S8eKTSRsWvq1+xgreWcXGzDXUmeZOI1qn3cHyOjvhl376Idb1ETVbQ3Km5Hg8GjvaLoOyFQs/4tKh411lMQ3YURNYf3iLrSC)
    accessTokenExpiration: 30000
    refreshTokenExpiration: 60000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

email:
  gmail:
    id: ENC(DR0J+Ify50+A4JkKuXg4HNrWkcgfy4XLwofhJqpir4Y=)
    pw: ENC(cbu0+ZLXCzeousUvSD8d8hxy93PPRmIWOONbdwKcjfk=)